# Generated by Django 5.2.4 on 2025-07-14 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('account', models.CharField(max_length=20)),
                ('balance', models.BigIntegerField()),
                ('date_time', models.CharField(max_length=20)),
                ('type', models.IntegerField(choices=[(1, 'Deposit'), (-1, 'Withdrawal')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed', to='transactions.transactions')),
            ],
        ),
    ]
