# Generated by Django 5.2.4 on 2025-07-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsedtransaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedtransaction',
            name='account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parsedtransaction',
            name='balance',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
